// Generated by CoffeeScript 1.10.0
$(document).ready(function() {
  var at, bk, ch;
  bk = [];
  ch = 0;
  at = $('.article');
  $.getJSON('resources/tao-te-ching.json', function(j) {
    $.each(j, function(k, v) {
      bk.push(v);
    });
    at.html(bk[ch]);
  });
  $('.new').on('click', function() {
    ch = Math.floor(Math.random() * (81 - 2)) + 2;
    $(this).toggleClass('dark');
    at.fadeOut(1364, function() {
      at.html(bk[ch]);
      at.fadeIn(842);
    });
  });
});
